openapi: 3.0.3
title: CENTEF RAG API
version: 0.1.0
servers:
  - url: https://agent-api.example.com
paths:
  /chat:
    post:
      summary: Ask a question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                k:
                  type: integer
                  default: 8
                filter:
                  type: string
              required: [question]
      responses:
        '200':
          description: Answer and citations
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  contexts:
                    type: array
                    items:
                      type: object
  /ingest/docs:
    post:
      summary: Ingest PDF/PPTX as page-anchored chunks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_id: {type: string}
                uri: {type: string, description: gs:// path}
                title: {type: string}
                source_type: {type: string, enum: [pdf, pptx]}
                lang: {type: string}
              required: [source_id, uri, title]
      responses:
        '200': {description: OK}
  /ingest/av:
    post:
      summary: Ingest audio/video as time-anchored chunks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_id: {type: string}
                uri: {type: string, description: gs:// path}
                title: {type: string}
                source_type: {type: string, enum: [audio, video]}
                lang: {type: string}
              required: [source_id, uri, title]
      responses:
        '200': {description: OK}
  /ingest/images:
    post:
      summary: Ingest image with OCR/caption as chunk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_id: {type: string}
                uri: {type: string, description: gs:// path}
                title: {type: string}
                ocr_text: {type: string}
                caption: {type: string}
                lang: {type: string}
              required: [source_id, uri, title]
      responses:
        '200': {description: OK}
